# Generated by Django 4.2.13 on 2024-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="sen_versionsnummer",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
